### PR TITLE
Update styles

### PR DESCRIPTION
**Pull request by dislick**
A darker background and less aggressive box-shadow makes the popup look more modern and increases the readability of translations.

Here is a before/after screenshot of these changes.

proposed visual changes

### CODE REVIEW

**Comment by CennoxX** [comment]
I think a darker background would be interrupting.

**Comment by Lusito** [comment]
Not too much of a fan of this either. Could be done if it was optional (opt-in).

**Comment by dislick** [comment]
I understand. The background should not be darker as it currently is - I agree with both of you. However I think that we could make the body of the popup clear white to increase the contrast ratio of the translations. My recent commits makes the popup look like this:

newchanges

What do you think?

**Comment by CennoxX** [comment]
This works good for me. But the background in the second screen shot is still darker than before...

**Comment by dislick** [comment]
Fixed, background is now the same shade as before.

**Comment by Lusito** [comment]
Will take a look at this on sunday. I'm busy until then. But looking at the diff, the background isn't the same as you claim:

    -    "background": "rgba(128, 128, 128, 0.22)"
    +    "background": "rgba(0, 0, 0, 0.11)"

Still, I will check how it looks and see if it's okay.

**Comment by Lusito** [comment]
Sorry, it took me some time to get to it. The layer looks good, but I don't like the white background in the options page. If you can remove or adjust that, I can merge it.

**Pull request closed without merging**
